Feature: Introduction to ui-router

  Scenario: Route to start
    When I browse to the "/"
    When I click "navigation.start"
    Then I should be directed to "/start"
    Then I should see "Welcome!" text in "welcomeJumbotron.h1"
    Then I should see "to the exhibition of the most popular paintings" text in "welcomeJumbotron.p"

  Scenario: Route to Vertical Paintings
    When I browse to the "/"
    When I click "navigation.verticalPaintings"
    Then I should be directed to "/vPaintings"
    When I click "1" on the "image.verticalList"
    Then I should be directed to "/vPaintings/1"
    Then I should see "Mona Lisa" text in "painingDetails.title"
    Then I should see "Author: Leonardo da Vinci" text in "painingDetails.author"
    Then I should see "Location: Louvre" text in "painingDetails.location"
    Then I should see "Date: 1503–1517" text in "painingDetails.date"
    When I click "2" on the "image.verticalList"
    Then I should be directed to "/vPaintings/2"
    Then I should see "The Scream" text in "painingDetails.title"
    Then I should see "Author: Edvard Munch" text in "painingDetails.author"
    Then I should see "Location: National Gallery" text in "painingDetails.location"
    Then I should see "Date: 1893–1893" text in "painingDetails.date"
    When I click "3" on the "image.verticalList"
    Then I should be directed to "/vPaintings/3"
    Then I should see "Girl with a Pearl Earring" text in "painingDetails.title"
    Then I should see "Author: Jan Vermeer" text in "painingDetails.author"
    Then I should see "Location: Mauritshuis" text in "painingDetails.location"
    Then I should see "Date: 1665" text in "painingDetails.date"

  Scenario: Route to Horizontal Paintings
    When I browse to the "/"
    When I click "navigation.horizontalPaintings"
    Then I should be directed to "/hPaintings"
    When I click "1" on the "image.horizontalList"
    Then I should be directed to "/hPaintings/1"
    Then I should see "The Last Supper" text in "painingDetails.title"
    Then I should see "Author: Leonardo da Vinci" text in "painingDetails.author"
    Then I should see "Location: Santa Maria delle Grazie" text in "painingDetails.location"
    Then I should see "Date: 1495–1498" text in "painingDetails.date"
    When I click "2" on the "image.horizontalList"
    Then I should be directed to "/hPaintings/2"
    Then I should see "The Creation of Adam" text in "painingDetails.title"
    Then I should see "Author: Michelangelo" text in "painingDetails.author"
    Then I should see "Location: Sistine Chapel" text in "painingDetails.location"
    Then I should see "Date: 1512" text in "painingDetails.date"
